swissgrc/.github

profile/README.md
Add docker-azure-pipelines-openjdk repository
=> Add docker-azure-pipelines-openjdk

profile/README.md
Add https://github.com/swissgrc/chocolatey-packages repository
=> Add Chocolatey package repository

profile/README.md
Add Sonar Scanner for .NET image to README
=> Add Sonar Scanner for .NET image

.github/workflows/lint-image.yml, .github/workflows/publish-image.yml
Reusable workflows which can be used in the individual repos to build and lint Docker images
=> Reusable workflows for Docker images

.github/workflows/publish-image.yml
Adds ghcr.io to publish image workflow.
=> Publish to Docker Hub and ghcr.io

.github/workflows/publish-image.yml
Extract first image tag as imageRef for Trivy as Trivy does not support multiple image refs
=> Fix trivy image ref error

profile/README.md
Documents from which registries images are available
=> Mention registries from which images are available

profile/README.md
Add docker-azure-pipelines-packer repository to README
=> Add docker-azure-pipelines-packer repository

profile/README.md
Add new base images to the list
* Docker CLI
* Git
=> Add new base images

profile/README.md
Mention the new repository on to organization landing page.
=> Add .NET 7 Image to Readme

profile/README.md
Updates link to renamed OpenJDK repository
=> Rename OpenJDK repo

profile/README.md
Adds Sonar Scanner image for .NET 7
=> Add Sonar Scanner image for .NET 7

.github/workflows/sonarcloud.yml
Updates SonarCloud action to 2.0, which updates to Sonar CLI Scanner to 5.0 and Java 17
=> Update SonarCloud action

profile/README.md
Link to repo for Node.js 20 / .NET 7 Azure Pipelines image
=> Link .Node.js 20 repo

profile/README.md
Add Azure CLI with .NET 8 image
=> Add Azure CLI with .NET 8

profile/README.md
Add Node.js 20 with .NET 8 image
=> Add Node.js 20 with .NET 8

profile/README.md
Add Sonar Scanner for .NET 8 image
=> Add Sonar Scanner for .NET 8

profile/README.md
Add Eclipse Temurin OpenJDK 21 repository
=> Add Eclipse Temurin OpenJDK 21

profile/README.md
=> Add Statiq.Alerts

profile/README.md
Add Node.js 22 with .NET 8 image
=> Add Node.js 22 with .NET 8

profile/README.md
Adds the new .NET 9 repository to the overview
=> Add .NET 9 repository

profile/README.md
Update docs to include new repo
=> Add Azure CLI with .NET 9
